<?php

namespace Container7QxWmxh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_47heLuIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.47heLuI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.47heLuI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bookingListingService' => ['privates', 'App\\Service\\BookingListingService', 'getBookingListingServiceService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'bookingListingService' => 'App\\Service\\BookingListingService',
            'serializer' => '?',
        ]);
    }
}
