<?php

namespace Container7QxWmxh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KYs3cIlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kYs3cIl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kYs3cIl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BookingCancelController::__invoke' => ['privates', '.service_locator.9uZQ_f_', 'get_ServiceLocator_9uZQFService', true],
            'App\\Controller\\BookingCreateController::__invoke' => ['privates', '.service_locator.ati0bbA', 'get_ServiceLocator_Ati0bbAService', true],
            'App\\Controller\\BookingListingController::__invoke' => ['privates', '.service_locator.47heLuI', 'get_ServiceLocator_47heLuIService', true],
            'App\\Controller\\EventCreateController::__invoke' => ['privates', '.service_locator.LvZ95kN', 'get_ServiceLocator_LvZ95kNService', true],
            'App\\Controller\\EventDisplayController::__invoke' => ['privates', '.service_locator.4JBgsla', 'get_ServiceLocator_4JBgslaService', true],
            'App\\Controller\\EventFilterController::__invoke' => ['privates', '.service_locator.RyGWgq7', 'get_ServiceLocator_RyGWgq7Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\BookingCancelController:__invoke' => ['privates', '.service_locator.9uZQ_f_', 'get_ServiceLocator_9uZQFService', true],
            'App\\Controller\\BookingCancelController' => ['privates', '.service_locator.9uZQ_f_', 'get_ServiceLocator_9uZQFService', true],
            'App\\Controller\\BookingCreateController:__invoke' => ['privates', '.service_locator.ati0bbA', 'get_ServiceLocator_Ati0bbAService', true],
            'App\\Controller\\BookingCreateController' => ['privates', '.service_locator.ati0bbA', 'get_ServiceLocator_Ati0bbAService', true],
            'App\\Controller\\BookingListingController:__invoke' => ['privates', '.service_locator.47heLuI', 'get_ServiceLocator_47heLuIService', true],
            'App\\Controller\\BookingListingController' => ['privates', '.service_locator.47heLuI', 'get_ServiceLocator_47heLuIService', true],
            'App\\Controller\\EventCreateController:__invoke' => ['privates', '.service_locator.LvZ95kN', 'get_ServiceLocator_LvZ95kNService', true],
            'App\\Controller\\EventCreateController' => ['privates', '.service_locator.LvZ95kN', 'get_ServiceLocator_LvZ95kNService', true],
            'App\\Controller\\EventDisplayController:__invoke' => ['privates', '.service_locator.4JBgsla', 'get_ServiceLocator_4JBgslaService', true],
            'App\\Controller\\EventDisplayController' => ['privates', '.service_locator.4JBgsla', 'get_ServiceLocator_4JBgslaService', true],
            'App\\Controller\\EventFilterController:__invoke' => ['privates', '.service_locator.RyGWgq7', 'get_ServiceLocator_RyGWgq7Service', true],
            'App\\Controller\\EventFilterController' => ['privates', '.service_locator.RyGWgq7', 'get_ServiceLocator_RyGWgq7Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\BookingCancelController::__invoke' => '?',
            'App\\Controller\\BookingCreateController::__invoke' => '?',
            'App\\Controller\\BookingListingController::__invoke' => '?',
            'App\\Controller\\EventCreateController::__invoke' => '?',
            'App\\Controller\\EventDisplayController::__invoke' => '?',
            'App\\Controller\\EventFilterController::__invoke' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\BookingCancelController:__invoke' => '?',
            'App\\Controller\\BookingCancelController' => '?',
            'App\\Controller\\BookingCreateController:__invoke' => '?',
            'App\\Controller\\BookingCreateController' => '?',
            'App\\Controller\\BookingListingController:__invoke' => '?',
            'App\\Controller\\BookingListingController' => '?',
            'App\\Controller\\EventCreateController:__invoke' => '?',
            'App\\Controller\\EventCreateController' => '?',
            'App\\Controller\\EventDisplayController:__invoke' => '?',
            'App\\Controller\\EventDisplayController' => '?',
            'App\\Controller\\EventFilterController:__invoke' => '?',
            'App\\Controller\\EventFilterController' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
