<?php

namespace Container7QxWmxh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookingListingServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\BookingListingService' shared autowired service.
     *
     * @return \App\Service\BookingListingService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/BookingListingService.php';
        include_once \dirname(__DIR__, 4).'/src/Assembler/Input/BookingListingDTOAssembler.php';
        include_once \dirname(__DIR__, 4).'/src/Assembler/Output/BookingInfoDataDTOAssembler.php';

        return $container->privates['App\\Service\\BookingListingService'] = new \App\Service\BookingListingService(($container->privates['App\\Repository\\BookingRepository'] ?? $container->load('getBookingRepositoryService')), new \App\Assembler\Input\BookingListingDTOAssembler(($container->privates['validator'] ?? $container->getValidatorService())), new \App\Assembler\Output\BookingInfoDataDTOAssembler());
    }
}
