<?php

namespace Container7QxWmxh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventCreateServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\EventCreateService' shared autowired service.
     *
     * @return \App\Service\EventCreateService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/EventCreateService.php';
        include_once \dirname(__DIR__, 4).'/src/Assembler/Input/EventCreateDTOAssembler.php';

        return $container->privates['App\\Service\\EventCreateService'] = new \App\Service\EventCreateService(new \App\Assembler\Input\EventCreateDTOAssembler(($container->privates['validator'] ?? $container->getValidatorService())), ($container->privates['App\\Repository\\EventRepository'] ?? $container->load('getEventRepositoryService')));
    }
}
