<?php

namespace Container7QxWmxh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventDisplayServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\EventDisplayService' shared autowired service.
     *
     * @return \App\Service\EventDisplayService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/EventDisplayService.php';
        include_once \dirname(__DIR__, 4).'/src/Assembler/Input/EventDisplayDTOAssembler.php';
        include_once \dirname(__DIR__, 4).'/src/Assembler/Output/EventInfoDataDTOAssembler.php';

        return $container->privates['App\\Service\\EventDisplayService'] = new \App\Service\EventDisplayService(($container->privates['App\\Repository\\EventRepository'] ?? $container->load('getEventRepositoryService')), new \App\Assembler\Input\EventDisplayDTOAssembler(($container->privates['validator'] ?? $container->getValidatorService())), ($container->privates['App\\Assembler\\Output\\EventInfoDataDTOAssembler'] ??= new \App\Assembler\Output\EventInfoDataDTOAssembler()));
    }
}
