<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7QxWmxh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7QxWmxh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7QxWmxh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7QxWmxh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7QxWmxh\App_KernelDevDebugContainer([
    'container.build_hash' => '7QxWmxh',
    'container.build_id' => 'eba6d94b',
    'container.build_time' => 1754849508,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7QxWmxh');
