<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYGouAma\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYGouAma/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerYGouAma.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerYGouAma\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerYGouAma\App_KernelTestDebugContainer([
    'container.build_hash' => 'YGouAma',
    'container.build_id' => '25757d10',
    'container.build_time' => 1754851698,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYGouAma');
