<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'api_genid' => [['id'], ['_controller' => 'api_platform.action.not_exposed', '_api_respond' => 'true'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/.well-known/genid']], [], [], []],
    'api_errors' => [['status'], ['_controller' => 'api_platform.action.not_exposed', 'status' => '500'], ['status' => '\\d+'], [['variable', '/', '\\d+', 'status', true], ['text', '/api/errors']], [], [], []],
    'api_validation_errors' => [['id'], ['_controller' => 'api_platform.action.not_exposed'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/validation_errors']], [], [], []],
    'api_entrypoint' => [['index', '_format'], ['_controller' => 'api_platform.action.entrypoint', '_format' => '', '_api_respond' => 'true', 'index' => 'index'], ['index' => 'index'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', 'index', 'index', true], ['text', '/api']], [], [], []],
    'api_doc' => [['_format'], ['_controller' => 'api_platform.action.documentation', '_format' => '', '_api_respond' => 'true'], [], [['variable', '.', '[^/]++', '_format', true], ['text', '/api/docs']], [], [], []],
    'api_jsonld_context' => [['shortName', '_format'], ['_controller' => 'api_platform.jsonld.action.context', '_format' => 'jsonld', '_api_respond' => 'true'], ['shortName' => '[^.]+', '_format' => 'jsonld'], [['variable', '.', 'jsonld', '_format', true], ['variable', '/', '[^.]+', 'shortName', true], ['text', '/api/contexts']], [], [], []],
    'booking_cancel' => [['id'], ['_controller' => 'App\\Controller\\BookingCancelController'], [], [['text', '/cancel'], ['variable', '/', '[^/]++', 'id', true], ['text', '/bookings']], [], [], []],
    'booking_create' => [[], ['_controller' => 'App\\Controller\\BookingCreateController'], [], [['text', '/bookings']], [], [], []],
    'booking_list' => [['id'], ['_controller' => 'App\\Controller\\BookingListingController'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/bookings']], [], [], []],
    'event_create' => [[], ['_controller' => 'App\\Controller\\EventCreateController'], [], [['text', '/events']], [], [], []],
    'event_display' => [['id'], ['_controller' => 'App\\Controller\\EventDisplayController'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/events']], [], [], []],
    'event_filter_list' => [[], ['_controller' => 'App\\Controller\\EventFilterController'], [], [['text', '/events']], [], [], []],
];
