<?php

namespace ContainerYGouAma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9uZQFService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.9uZQ_f_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9uZQ_f_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bookingCancelService' => ['privates', 'App\\Service\\BookingCancelService', 'getBookingCancelServiceService', true],
        ], [
            'bookingCancelService' => 'App\\Service\\BookingCancelService',
        ]);
    }
}
