<?php

namespace ContainerYGouAma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_CacheConnection_RM7HMj_Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.cache_connection.RM7HMj.' shared service.
     *
     * @return \Symfony\Component\Cache\Adapter\AbstractAdapter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.cache_connection.RM7HMj.'] = \Symfony\Component\Cache\Adapter\AbstractAdapter::createConnection('redis://redis:6379?class=Predis\\Client', ['lazy' => true]);
    }
}
