<?php

namespace ContainerYGouAma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4JBgslaService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.4JBgsla' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4JBgsla'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'eventDisplayService' => ['services', 'App\\Service\\EventDisplayService', 'getEventDisplayServiceService', true],
        ], [
            'eventDisplayService' => 'App\\Service\\EventDisplayService',
        ]);
    }
}
