<?php

namespace ContainerYGouAma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LvZ95kNService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.LvZ95kN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LvZ95kN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'eventCreateService' => ['services', 'App\\Service\\EventCreateService', 'getEventCreateServiceService', true],
        ], [
            'eventCreateService' => 'App\\Service\\EventCreateService',
        ]);
    }
}
