<?php

namespace ContainerYGouAma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ati0bbAService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.ati0bbA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ati0bbA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bookingCreateService' => ['privates', 'App\\Service\\BookingCreateService', 'getBookingCreateServiceService', true],
        ], [
            'bookingCreateService' => 'App\\Service\\BookingCreateService',
        ]);
    }
}
