<?php

namespace ContainerYGouAma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_StateProcessor_SerializeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'api_platform.state_processor.serialize' shared service.
     *
     * @return \ApiPlatform\State\Processor\SerializeProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/State/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/State/Processor/SerializeProcessor.php';

        return $container->privates['api_platform.state_processor.serialize'] = new \ApiPlatform\State\Processor\SerializeProcessor(($container->privates['api_platform.hydra.processor.link'] ?? $container->load('getApiPlatform_Hydra_Processor_LinkService')), ($container->privates['serializer'] ?? $container->getSerializerService()), ($container->privates['api_platform.serializer.context_builder.filter'] ?? $container->getApiPlatform_Serializer_ContextBuilder_FilterService()));
    }
}
