<?php

namespace ContainerYGouAma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_StateProvider_AccessCheckerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'api_platform.state_provider.access_checker' shared service.
     *
     * @return \ApiPlatform\Symfony\Security\State\AccessCheckerProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Symfony/Security/State/AccessCheckerProvider.php';

        return $container->privates['api_platform.state_provider.access_checker'] = new \ApiPlatform\Symfony\Security\State\AccessCheckerProvider(($container->privates['api_platform.swagger_ui.provider'] ?? $container->load('getApiPlatform_SwaggerUi_ProviderService')), ($container->privates['api_platform.security.resource_access_checker'] ?? $container->getApiPlatform_Security_ResourceAccessCheckerService()));
    }
}
