<?php

namespace ContainerYGouAma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookingCreateServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\BookingCreateService' shared autowired service.
     *
     * @return \App\Service\BookingCreateService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/BookingCreateService.php';

        return $container->privates['App\\Service\\BookingCreateService'] = new \App\Service\BookingCreateService(($container->privates['App\\Repository\\BookingRepository'] ?? $container->load('getBookingRepositoryService')), ($container->privates['App\\Repository\\EventRepository'] ?? $container->load('getEventRepositoryService')), ($container->privates['App\\Assembler\\Input\\BookingCreateDTOAssembler'] ?? $container->load('getBookingCreateDTOAssemblerService')));
    }
}
