<?php

namespace ContainerYGouAma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookingCancelDTOAssemblerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Assembler\Input\BookingCancelDTOAssembler' shared autowired service.
     *
     * @return \App\Assembler\Input\BookingCancelDTOAssembler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Assembler/Input/BookingCancelDTOAssembler.php';

        return $container->privates['App\\Assembler\\Input\\BookingCancelDTOAssembler'] = new \App\Assembler\Input\BookingCancelDTOAssembler(($container->privates['validator'] ?? $container->getValidatorService()));
    }
}
