<?php

namespace ContainerYGouAma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookingRepositoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Repository\BookingRepository' shared autowired service.
     *
     * @return \App\Repository\BookingRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/BookingRepository.php';

        return $container->privates['App\\Repository\\BookingRepository'] = new \App\Repository\BookingRepository(($container->services['cache.app'] ?? $container->load('getCache_AppService')), ($container->privates['App\\Manager\\ConnectionManager'] ?? $container->load('getConnectionManagerService')));
    }
}
