<?php

namespace ContainerYGouAma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookingInfoDataDTOAssemblerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Assembler\Output\BookingInfoDataDTOAssembler' shared autowired service.
     *
     * @return \App\Assembler\Output\BookingInfoDataDTOAssembler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Assembler/Output/BookingInfoDataDTOAssembler.php';

        return $container->privates['App\\Assembler\\Output\\BookingInfoDataDTOAssembler'] = new \App\Assembler\Output\BookingInfoDataDTOAssembler();
    }
}
