<?php

namespace ContainerYGouAma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookingCancelServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\BookingCancelService' shared autowired service.
     *
     * @return \App\Service\BookingCancelService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/BookingCancelService.php';

        return $container->privates['App\\Service\\BookingCancelService'] = new \App\Service\BookingCancelService(($container->privates['App\\Repository\\BookingRepository'] ?? $container->load('getBookingRepositoryService')), ($container->privates['App\\Repository\\EventRepository'] ?? $container->load('getEventRepositoryService')), ($container->privates['App\\Assembler\\Input\\BookingCancelDTOAssembler'] ?? $container->load('getBookingCancelDTOAssemblerService')));
    }
}
