<?php

namespace ContainerYGouAma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConnectionManagerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Manager\ConnectionManager' shared autowired service.
     *
     * @return \App\Manager\ConnectionManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Manager/ConnectionManager.php';

        return $container->privates['App\\Manager\\ConnectionManager'] = new \App\Manager\ConnectionManager(($container->privates['PDO.write'] ??= new \PDO('mysql:host=avoris-php84-symfony62-mysql;dbname=mysql_symfony_avoris', 'avoris', 'avoris')), ($container->privates['PDO.read'] ??= new \PDO('mysql:host=avoris-php84-symfony62-mysql;dbname=mysql_symfony_avoris', 'avoris', 'avoris')));
    }
}
