<?php

namespace ContainerYGouAma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventCreateServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Service\EventCreateService' shared service.
     *
     * @return \App\Service\EventCreateService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/EventCreateService.php';

        return $container->services['App\\Service\\EventCreateService'] = new \App\Service\EventCreateService();
    }
}
