<?php

namespace ContainerYGouAma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventOptionalFilterDisplayServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Service\EventOptionalFilterDisplayService' shared service.
     *
     * @return \App\Service\EventOptionalFilterDisplayService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/EventOptionalFilterDisplayService.php';

        return $container->services['App\\Service\\EventOptionalFilterDisplayService'] = new \App\Service\EventOptionalFilterDisplayService();
    }
}
