<?php

namespace ContainerYGouAma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventCreateControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\EventCreateController' shared autowired service.
     *
     * @return \App\Controller\EventCreateController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/EventCreateController.php';

        $container->services['App\\Controller\\EventCreateController'] = $instance = new \App\Controller\EventCreateController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\EventCreateController', $container));

        return $instance;
    }
}
