<?php

namespace ContainerYGouAma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventDisplayServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Service\EventDisplayService' shared service.
     *
     * @return \App\Service\EventDisplayService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/EventDisplayService.php';

        return $container->services['App\\Service\\EventDisplayService'] = new \App\Service\EventDisplayService();
    }
}
