<?php

namespace ContainerYGouAma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPDO_ReadService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'PDO.read' shared autowired service.
     *
     * @return \PDO
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PDO.read'] = new \PDO('mysql:host=avoris-php84-symfony62-mysql;dbname=mysql_symfony_avoris', 'avoris', 'avoris');
    }
}
